spring:
  banner:
      location: banner.txt
  datasource:
    url: jdbc:mysql://localhost:3306/library?useSSL=false
    username: root
    password: admin
    tomcat:
      initial-size: 5
  jpa:
    hibernate:
      ddl-auto: create
  profiles: test
name: test-YAML
environment: test
servers:
  - www.abc.test.com
  - www.xyz.test.com